image: python:3.5-alpine

variables:
  DEMO_OUTPUT: "$CI_PROJECT_DIR/public/demo"
  DEMO_STORAGE: "$CI_PROJECT_DIR/demo-data"
  DEMO_THEME: "$CI_PROJECT_DIR/pelican-alchemy/alchemy"
  ISSYOURS_DEBUG: 1
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/pip-cache"
  VENVDIR: "$CI_PROJECT_DIR/venv"
  # ISSYOURS_GITHUB_TOKEN: set via GitLab CI web interface

cache:
  paths:
    - demo-data
    - pelican-alchemy
    - pip-cache
    - venv

before_script:
  - python --version
  - python -m venv venv
  - source venv/bin/activate

pages:
  script:
    - apk add
        git
        make
        rsync
    - mkdir mkdocs_source
    - rsync
        -Rr . mkdocs_source
        --exclude demo-data
        --exclude pelican-alchemy
        --exclude pip-cache
        --exclude venv
    - pip install
        mkdocs
        mkdocs-material
        pygments
    - mkdocs build
    - git clone --depth 1 "https://github.com/nairobilug/pelican-alchemy.git"
      || (
        git -C "$DEMO_THEME" fetch --depth 1 &&
        git -C "$DEMO_THEME" reset --hard origin/master
      )
    - make demo
  artifacts:
    paths:
      - public/
  only:
    - website
