image: python:3.5-alpine

variables:
  DEMO_OUTPUT: "$CI_PROJECT_DIR/public/demo"
  DEMO_STORAGE: "$CI_PROJECT_DIR/demo-data"
  DOCS_OUTPUT: "$CI_PROJECT_DIR/public"
  ISSYOURS_DEBUG: 1
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/pip-cache"
  VENVDIR: "$CI_PROJECT_DIR/venv"
  # ISSYOURS_GITHUB_TOKEN: set via GitLab CI web interface

cache: &global_cache
  paths:
    - demo-data
    - pip-cache
    - venv
  key: shared-cache-4  # increment suffix to drop cache

before_script:
  - apk add make

test:
  script:
    - make test
  cache:
    <<: *global_cache
    policy: pull

pages:
  script:
    - make docs
    - make demo
  artifacts:
    paths:
      - public/
  only:
    - website
