image: python:3.5-alpine

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/pip-cache"
  DEMO_OUTPUT: "$CI_PROJECT_DIR/public/demo"
  DEMO_STORAGE: "$CI_PROJECT_DIR/demo-data"
  DEMO_THEME: "$CI_PROJECT_DIR/pelican-alchemy/alchemy"
  VENVDIR: "$CI_PROJECT_DIR/venv"
  ISSYOURS_DEBUG: 1
  # ISSYOURS_GITHUB_TOKEN: set via GitLab CI web interface

cache:
  paths:
    - pip-cache
    - venv
    - demo-data
    - pelican-alchemy

before_script:
  - python --version
  - python -m venv venv
  - source venv/bin/activate

pages:
  script:
    - apk add rsync make
    - mkdir mkdocs_source
    - rsync
        -Rr . mkdocs_source
        --exclude venv
        --exclude pip-cache
    - pip install
        mkdocs
        mkdocs-material
        pygments
    - mkdocs build
    - git clone --depth 1 "https://github.com/nairobilug/pelican-alchemy.git" || true
    - make demo
  artifacts:
    paths:
      - public/
  only:
    - website
