image: python:3.5-alpine

variables:
  DEMO_OUTPUT: "$CI_PROJECT_DIR/public/demo"
  DEMO_STORAGE: "$CI_PROJECT_DIR/demo-data"
  ISSYOURS_DEBUG: 1
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/pip-cache"
  VENVDIR: "$CI_PROJECT_DIR/venv"
  # ISSYOURS_GITHUB_TOKEN: set via GitLab CI web interface

cache:
  paths:
    - demo-data
    - pip-cache
    - venv

pages:
  script:
    - apk add make
    - make docs
    - make demo
  artifacts:
    paths:
      - public/
  only:
    - website
