site_url: https://issyours.ml
site_name: Issyours
site_description: Read-only archive for any issue tracker
site_author: Vitaly Potyarkin
site_dir: !!python/object/apply:os.getenv ["DOCS_OUTPUT"]

repo_url: https://github.com/sio/issyours
repo_name: sio / issyours
edit_uri: ''

nav:
  - Overview: index.md
  - Quickstart:
    - Demo: demonstration.md
    - Getting started: quickstart.md
  - Documentation:
    - Configuration: configuring.md
    - GitHub data source: github.md
    - Themes: themes.md
  - Misc:
    - Initial design: design.md
    - Distributed issue tracking: distributed.md
  - Changelog: changelog.md
  - Copyright: copying.md

docs_dir: docs
theme:
  name: material
  palette:
    primary: cyan
    accent: cyan
  static_templates:
    - 404.html

google_analytics:
  - UA-121532727-4
  - issyours.ml

markdown_extensions:
  - codehilite:
      guess_lang: false
  - toc:
      permalink: '#'
